bind r source-file ~/.tmux.conf

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Use vim keybindings for navigating copy mode
setw -g mode-keys vi

# When creating a new window or pane, automatically change to the directory of
# the current window or pane.
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
